### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by the-Blue-Falcon** [PowerScript/KatanaFramework#22]
Okay so I did a fresh clone and installed it, everything was okay but on running `ktf.console`, this error popped out:
```
Traceback (most recent call last):
  File "./ktf.console", line 53, in <module>
    LoadGlobalVariables()
  File "/root/Desktop/Tools/Pentest/KatanaFramework/core/Internal.py", line 512, in LoadGlobalVariables
    data_file   = open('core/logs/variables.globals.json','r')
IOError: [Errno 2] No such file or directory: 'core/logs/variables.globals.json'
```

**Comment by looplife55** [comment]
+1

**Comment by RedToor** [comment]
Please add info about your distrubution (Debian, CentOS, etc) and version, and [see].(https://github.com/PowerScript/KatanaFramework/issues/20#issuecomment-398502966)

**Comment by trollmad3** [comment]
The file may be existing but may have a different path.

**Comment by Nabiaz** [comment]
[Exception]([SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:727))

when i run  a modules then show this problem. how fix it?

![screenshot at 2019-01-22 02-59-56](https://user-images.githubusercontent.com/44144041/51498833-38939d00-1df2-11e9-9637-c2fa51f4785f.png)

**Comment by Nabiaz** [comment]
please fixed this problem
wrong version _
ssl.c
![screenshot at 2019-01-22 03-05-53](https://user-images.githubusercontent.com/44144041/51498987-c7a0b500-1df2-11e9-8aa9-2bf70cada699.png)

**Comment by anonymousforce** [comment]
> please fixed this problem
> wrong version _
> ssl.c
> ![screenshot at 2019-01-22 03-05-53](https://user-images.githubusercontent.com/44144041/51498987-c7a0b500-1df2-11e9-8aa9-2bf70cada699.png)

PLEASE FIX THIS I GOT A SAME PROBLEM!

**Comment by k4r0s** [comment]
> please fixed this problem
> wrong version _
> ssl.c
> ![screenshot at 2019-01-22 03-05-53](https://user-images.githubusercontent.com/44144041/51498987-c7a0b500-1df2-11e9-8aa9-2bf70cada699.png)

same problem help please!

**Comment by k4r0s** [comment]
> @Nabiaz I had that same problem. type `ping <INSERT URL YOU ARE TRYING TO FIND ADMIN PANELS FOR>` and see if it works.

not working

**Comment by nonanik112** [comment]
ktf.console                

Traceback (most recent call last):
  File "/usr/share/KatanaFramework/ktf.console", line 9, in <module>
    from core.MainListLibrary import *
  File "/usr/share/KatanaFramework/core/MainListLibrary.py", line 10, in <module>
    from Internal import (

Linux version Purple New 2023 Version
