### ISSUE TITLE
ModuleNotFoundError: No module named 'Internal'

### ISSUE THREAD

**Issue by VanishingTacos** [PowerScript/KatanaFramework#28]
having a bit of troubles getting it to work on Arch Linux. Anytime I run ktf.console it give the following:

```Traceback (most recent call last):
  File "ktf.console", line 9, in <module>
    from core.MainListLibrary import *
  File "/usr/share/KatanaFramework/core/MainListLibrary.py", line 10, in <module>
    from Internal import (
ModuleNotFoundError: No module named 'Internal'
```

**Comment by shaggywesley** [comment]
same exact error here but I'm on kali

**Comment by zer0-1nd3x** [comment]
how do you fixed yours please i'm currently facing this error
