### ISSUE TITLE
ktf.console not working (ModuleNotFoundError: No module named 'Internal')

### ISSUE THREAD

**Issue by Balhech** [PowerScript/KatanaFramework#46]
python3 ktf.console
Traceback (most recent call last):
  File "/root/KatanaFramework/ktf.console", line 9, in <module>
    from core.MainListLibrary import *
  File "/root/KatanaFramework/core/MainListLibrary.py", line 10, in <module>
    from Internal import (
ModuleNotFoundError: No module named 'Internal'

anyone please?

**Comment by Twinsghost** [comment]
> python3 ktf.console Traceback (most recent call last): File "/root/KatanaFramework/ktf.console", line 9, in from core.MainListLibrary import * File "/root/KatanaFramework/core/MainListLibrary.py", line 10, in from Internal import ( ModuleNotFoundError: No module named 'Internal'
> 
> anyone please?

use python2 ktf.console or ktf.gui

**Comment by zer0-1nd3x** [comment]
python2 ktf.console
Traceback (most recent call last):
File "/root/KatanaFramework/ktf.console", line 9, in
from core.MainListLibrary import *
File "/root/KatanaFramework/core/MainListLibrary.py", line 10, in
from Internal import (
ModuleNotFoundError: No module named 'Internal'

How can i fix this error please?
