### ISSUE TITLE
err

### ISSUE THREAD

**Issue by tony25tony** [PowerScript/KatanaFramework#47]
sudo python install
  File "/root/Tools/KatanaFramework/install", line 24
    print ""
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("")?

**Comment by ghost6183** [comment]
Try (python2.7 install)

**Comment by krunal8055** [comment]
Used Python2.7 install and it worked thank you buddy

**Comment by devil355** [comment]
ktf.console
Traceback (most recent call last):
  File "/usr/share/KatanaFramework/ktf.console", line 9, in <module>
    from core.MainListLibrary import *
  File "/usr/share/KatanaFramework/core/MainListLibrary.py", line 10, in <module>
    from Internal import (
ModuleNotFoundError: No module named 'Internal'
